FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3

RUN install_packages wget unzip curl
RUN apt-get update && apt-get install kbd git patch

RUN mkdir -p /usr/src/mydash

WORKDIR /usr/src/mydash

RUN git clone https://github.com/boppreh/keyboard

COPY keyboard.patch /usr/src/mydash/keyboard/

COPY start.py ./

RUN cd keyboard && patch -p1 < keyboard.patch

ENV PYTHONPATH="/usr/src/mydash/keyboard:${PYTHONPATH}"

CMD python start.py #keyboard/examples/stdin_stdout_events.py